import re


class MP:
    mp_map = [
        ######################################################################################
        # Пакет: ipoteka #####################################################################
        ######################################################################################
        {"descr": 'test_bdg', "fltrs": ["_mobapptest_", "_test_"]},

        ######################################################################################
        # Пакет: ipoteka #####################################################################
        ######################################################################################
        {"descr": 'b2c_all_ipoteka_bdg', "fltrs": ["b2c_.*_general_main_ipoteka_mix_search", ]},

        ######################################################################################
        # Пакет: b2b #########################################################################
        ######################################################################################
        {"descr": 'msk_b2b_own_search_bdg', "fltrs": ["b2b_(dmo|bmo|mo|msk)_general_null_own_desk_search", ]},
        {"descr": 'spb_b2b_own_search_bdg', "fltrs": ["b2b_spb_general_null_own_desk_search", ]},
        {"descr": 'p4c_b2b_own_search_bdg',
         "fltrs": ["b2b_(kazan|nn|krasnoyarsk|voronezh)_general_null_own_desk_search", ]},
        {"descr": 'reg18_b2b_own_search_bdg', "fltrs": ["b2b_chelyabinsk_general_null_own_desk_search",
                                                        "b2b_ekb_general_null_own_desk_search",
                                                        "b2b_irkutsk_general_null_own_desk_search",
                                                        "b2b_kaliningrad_general_null_own_desk_search",
                                                        "b2b_kemerovo_general_null_own_desk_search",
                                                        "b2b_krasnodar_general_null_own_desk_search",
                                                        "b2b_novosibirsk_general_null_own_desk_search",
                                                        "b2b_omsk_general_null_own_desk_search",
                                                        "b2b_perm_general_null_own_desk_search",
                                                        "b2b_rostov_general_null_own_desk_search",
                                                        "b2b_samara_general_null_own_desk_search",
                                                        "b2b_sevastopol_general_null_own_desk_search",
                                                        "b2b_sochi_general_null_own_desk_search",
                                                        "b2b_stavropol_general_null_own_desk_search",
                                                        "b2b_tyumen_general_null_own_desk_search",
                                                        "b2b_ufa_general_null_own_desk_search",
                                                        "b2b_volgograd_general_null_own_desk_search",
                                                        "b2b_yalta_general_null_own_desk_search",
                                                        ]},
        {"descr": 'oth_b2b_own_search_bdg', "fltrs": [
            "b2b_arhangelsk_general_null_own_desk_search",
            "b2b_astrahan_general_null_own_desk_search",
            "b2b_barnaul_general_null_own_desk_search",
            "b2b_belgorod_general_null_own_desk_search",
            "b2b_bryansk_general_null_own_desk_search",
            "b2b_cheboksary_general_null_own_desk_search",
            "b2b_habarovsk_general_null_own_desk_search",
            "b2b_ivanovo_general_null_own_desk_search",
            "b2b_izhevsk_general_null_own_desk_search",
            "b2b_kaluga_general_null_own_desk_search",
            "b2b_kirov_general_null_own_desk_search",
            "b2b_kostroma_general_null_own_desk_search",
            "b2b_kurgan_general_null_own_desk_search",
            "b2b_kursk_general_null_own_desk_search",
            "b2b_lipetsk_general_null_own_desk_search",
            "b2b_mahachkala_general_null_own_desk_search",
            "b2b_novgorod_general_null_own_desk_search",
            "b2b_orel_general_null_own_desk_search",
            "b2b_orenburg_general_null_own_desk_search",
            "b2b_penza_general_null_own_desk_search",
            "b2b_pskov_general_null_own_desk_search",
            "b2b_ryazan_general_null_own_desk_search",
            "b2b_saratov_general_null_own_desk_search",
            "b2b_smolensk_general_null_own_desk_search",
            "b2b_surgut_general_null_own_desk_search",
            "b2b_tambov_general_null_own_desk_search",
            "b2b_tomsk_general_null_own_desk_search",
            "b2b_tula_general_null_own_desk_search",
            "b2b_tver_general_null_own_desk_search",
            "b2b_ulanude_general_null_own_desk_search",
            "b2b_ulyanovsk_general_null_own_desk_search",
            "b2b_vladimir_general_null_own_desk_search",
            "b2b_vladivostok_general_null_own_desk_search",
            "b2b_yaroslavl_general_null_own_desk_search",
        ]},

        {"descr": 'msk_b2b_own_network_bdg', "fltrs": ["b2b_(dmo|bmo|mo|msk)_.*_own_desk_network", ]},
        {"descr": 'spb_b2b_own_network_bdg', "fltrs": ["b2b_spb_.*_own_desk_network", ]},
        {"descr": 'p4c_b2b_own_network_bdg', "fltrs": ["b2b_(kazan|nn|krasnoyarsk|voronezh)_.*_own_desk_network", ]},
        {"descr": 'reg18_b2b_own_network_bdg', "fltrs": ["b2b_chelyabinsk_.*_own_desk_network",
                                                         "b2b_ekb_.*_own_desk_network",
                                                         "b2b_irkutsk_.*_own_desk_network",
                                                         "b2b_kaliningrad_.*_own_desk_network",
                                                         "b2b_kemerovo_.*_own_desk_network",
                                                         "b2b_krasnodar_.*_own_desk_network",
                                                         "b2b_novosibirsk_.*_own_desk_network",
                                                         "b2b_omsk_.*_own_desk_network",
                                                         "b2b_perm_.*_own_desk_network",
                                                         "b2b_rostov_.*_own_desk_network",
                                                         "b2b_samara_.*_own_desk_network",
                                                         "b2b_sevastopol_.*_own_desk_network",
                                                         "b2b_sochi_.*_own_desk_network",
                                                         "b2b_stavropol_.*_own_desk_network",
                                                         "b2b_tyumen_.*_own_desk_network",
                                                         "b2b_ufa_.*_own_desk_network",
                                                         "b2b_volgograd_.*_own_desk_network",
                                                         "b2b_yalta_.*_own_desk_network",
                                                         ]},
        {"descr": 'oth_b2b_own_network_bdg', "fltrs": [
            "b2b_arhangelsk_.*_own_desk_network",
            "b2b_astrahan_.*_own_desk_network",
            "b2b_barnaul_.*_own_desk_network",
            "b2b_belgorod_.*_own_desk_network",
            "b2b_bryansk_.*_own_desk_network",
            "b2b_cheboksary_.*_own_desk_network",
            "b2b_habarovsk_.*_own_desk_network",
            "b2b_ivanovo_.*_own_desk_network",
            "b2b_izhevsk_.*_own_desk_network",
            "b2b_kaluga_.*_own_desk_network",
            "b2b_kirov_.*_own_desk_network",
            "b2b_kostroma_.*_own_desk_network",
            "b2b_kurgan_.*_own_desk_network",
            "b2b_kursk_.*_own_desk_network",
            "b2b_lipetsk_.*_own_desk_network",
            "b2b_mahachkala_.*_own_desk_network",
            "b2b_novgorod_.*_own_desk_network",
            "b2b_orel_.*_own_desk_network",
            "b2b_orenburg_.*_own_desk_network",
            "b2b_penza_.*_own_desk_network",
            "b2b_pskov_.*_own_desk_network",
            "b2b_ryazan_.*_own_desk_network",
            "b2b_saratov_.*_own_desk_network",
            "b2b_smolensk_.*_own_desk_network",
            "b2b_surgut_.*_own_desk_network",
            "b2b_tambov_.*_own_desk_network",
            "b2b_tomsk_.*_own_desk_network",
            "b2b_tula_.*_own_desk_network",
            "b2b_tver_.*_own_desk_network",
            "b2b_ulanude_.*_own_desk_network",
            "b2b_ulyanovsk_.*_own_desk_network",
            "b2b_vladimir_.*_own_desk_network",
            "b2b_vladivostok_.*_own_desk_network",
            "b2b_yaroslavl_.*_own_desk_network",
        ]},

        ######################################################################################
        # Пакет: brand_cian ##################################################################
        ######################################################################################
        {"descr": 'msk_brand_cian_bdg', "fltrs": ["b2c_(dmo|bmo|mo|msk)_brand_cian_all_mix_search", ]},
        {"descr": 'spb_brand_cian_bdg', "fltrs": ["b2c_spb_brand_cian_all_mix_search", ]},
        {"descr": 'p4c_brand_cian_bdg', "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_brand_cian_all_mix_search", ]},
        {"descr": 'reg18_brand_cian_bdg', "fltrs": ["b2c_chelyabinsk_brand_cian_all_mix_search",
                                                    "b2c_ekb_brand_cian_all_mix_search",
                                                    "b2c_irkutsk_brand_cian_all_mix_search",
                                                    "b2c_kaliningrad_brand_cian_all_mix_search",
                                                    "b2c_kemerovo_brand_cian_all_mix_search",
                                                    "b2c_krasnodar_brand_cian_all_mix_search",
                                                    "b2c_novosibirsk_brand_cian_all_mix_search",
                                                    "b2c_omsk_brand_cian_all_mix_search",
                                                    "b2c_perm_brand_cian_all_mix_search",
                                                    "b2c_rostov_brand_cian_all_mix_search",
                                                    "b2c_samara_brand_cian_all_mix_search",
                                                    "b2c_sevastopol_brand_cian_all_mix_search",
                                                    "b2c_sochi_brand_cian_all_mix_search",
                                                    "b2c_stavropol_brand_cian_all_mix_search",
                                                    "b2c_tyumen_brand_cian_all_mix_search",
                                                    "b2c_ufa_brand_cian_all_mix_search",
                                                    "b2c_volgograd_brand_cian_all_mix_search",
                                                    "b2c_yalta_brand_cian_all_mix_search",
                                                    ]},
        {"descr": 'oth_brand_cian_bdg', "fltrs": [
            "b2c_arhangelsk_brand_cian_all_mix_search",
            "b2c_astrahan_brand_cian_all_mix_search",
            "b2c_barnaul_brand_cian_all_mix_search",
            "b2c_belgorod_brand_cian_all_mix_search",
            "b2c_bryansk_brand_cian_all_mix_search",
            "b2c_cheboksary_brand_cian_all_mix_search",
            "b2c_habarovsk_brand_cian_all_mix_search",
            "b2c_ivanovo_brand_cian_all_mix_search",
            "b2c_izhevsk_brand_cian_all_mix_search",
            "b2c_kaluga_brand_cian_all_mix_search",
            "b2c_kirov_brand_cian_all_mix_search",
            "b2c_kostroma_brand_cian_all_mix_search",
            "b2c_kurgan_brand_cian_all_mix_search",
            "b2c_kursk_brand_cian_all_mix_search",
            "b2c_lipetsk_brand_cian_all_mix_search",
            "b2c_mahachkala_brand_cian_all_mix_search",
            "b2c_novgorod_brand_cian_all_mix_search",
            "b2c_orel_brand_cian_all_mix_search",
            "b2c_orenburg_brand_cian_all_mix_search",
            "b2c_penza_brand_cian_all_mix_search",
            "b2c_pskov_brand_cian_all_mix_search",
            "b2c_ryazan_brand_cian_all_mix_search",
            "b2c_saratov_brand_cian_all_mix_search",
            "b2c_smolensk_brand_cian_all_mix_search",
            "b2c_surgut_brand_cian_all_mix_search",
            "b2c_tambov_brand_cian_all_mix_search",
            "b2c_tomsk_brand_cian_all_mix_search",
            "b2c_tula_brand_cian_all_mix_search",
            "b2c_tver_brand_cian_all_mix_search",
            "b2c_ulanude_brand_cian_all_mix_search",
            "b2c_ulyanovsk_brand_cian_all_mix_search",
            "b2c_vladimir_brand_cian_all_mix_search",
            "b2c_vladivostok_brand_cian_all_mix_search",
            "b2c_yaroslavl_brand_cian_all_mix_search",
        ]},

        ######################################################################################
        # Пакет: commerce ####################################################################
        ######################################################################################
        {"descr": 'msk_com_mix_search_bdg', "fltrs": ["b2b_(bmo|dmo|msk)_general_null_com_mix_search", ]},
        {"descr": 'spb_com_mix_search_bdg', "fltrs": ["b2b_spb_general_null_com_mix_search", ]},
        {"descr": 'p4c_com_mix_search_bdg',
         "fltrs": ["b2b_(kazan|nn|krasnoyarsk|voronezh)_general_null_com_mix_search", ]},
        {"descr": 'reg18_com_mix_search_bdg', "fltrs": ["b2b_chelyabinsk_general_null_com_mix_search",
                                                        "b2b_ekb_general_null_com_mix_search",
                                                        "b2b_irkutsk_general_null_com_mix_search",
                                                        "b2b_kaliningrad_general_null_com_mix_search",
                                                        "b2b_kemerovo_general_null_com_mix_search",
                                                        "b2b_krasnodar_general_null_com_mix_search",
                                                        "b2b_novosibirsk_general_null_com_mix_search",
                                                        "b2b_omsk_general_null_com_mix_search",
                                                        "b2b_perm_general_null_com_mix_search",
                                                        "b2b_rostov_general_null_com_mix_search",
                                                        "b2b_samara_general_null_com_mix_search",
                                                        "b2b_sevastopol_general_null_com_mix_search",
                                                        "b2b_sochi_general_null_com_mix_search",
                                                        "b2b_stavropol_general_null_com_mix_search",
                                                        "b2b_tyumen_general_null_com_mix_search",
                                                        "b2b_ufa_general_null_com_mix_search",
                                                        "b2b_volgograd_general_null_com_mix_search",
                                                        "b2b_yalta_general_null_com_mix_search",
                                                        ]},
        {"descr": 'oth_com_mix_search_bdg', "fltrs": [
            "b2b_arhangelsk_general_null_com_mix_search",
            "b2b_astrahan_general_null_com_mix_search",
            "b2b_barnaul_general_null_com_mix_search",
            "b2b_belgorod_general_null_com_mix_search",
            "b2b_bryansk_general_null_com_mix_search",
            "b2b_cheboksary_general_null_com_mix_search",
            "b2b_habarovsk_general_null_com_mix_search",
            "b2b_ivanovo_general_null_com_mix_search",
            "b2b_izhevsk_general_null_com_mix_search",
            "b2b_kaluga_general_null_com_mix_search",
            "b2b_kirov_general_null_com_mix_search",
            "b2b_kostroma_general_null_com_mix_search",
            "b2b_kurgan_general_null_com_mix_search",
            "b2b_kursk_general_null_com_mix_search",
            "b2b_lipetsk_general_null_com_mix_search",
            "b2b_mahachkala_general_null_com_mix_search",
            "b2b_novgorod_general_null_com_mix_search",
            "b2b_orel_general_null_com_mix_search",
            "b2b_orenburg_general_null_com_mix_search",
            "b2b_penza_general_null_com_mix_search",
            "b2b_pskov_general_null_com_mix_search",
            "b2b_ryazan_general_null_com_mix_search",
            "b2b_saratov_general_null_com_mix_search",
            "b2b_smolensk_general_null_com_mix_search",
            "b2b_surgut_general_null_com_mix_search",
            "b2b_tambov_general_null_com_mix_search",
            "b2b_tomsk_general_null_com_mix_search",
            "b2b_tula_general_null_com_mix_search",
            "b2b_tver_general_null_com_mix_search",
            "b2b_ulanude_general_null_com_mix_search",
            "b2b_ulyanovsk_general_null_com_mix_search",
            "b2b_vladimir_general_null_com_mix_search",
            "b2b_vladivostok_general_null_com_mix_search",
            "b2b_yaroslavl_general_null_com_mix_search",
        ]},

        {"descr": 'msk_com_mix_network_bdg', "fltrs": ["b2b_(mo|msk)_general_main_com_mix_network", ]},
        {"descr": 'spb_com_mix_network_bdg', "fltrs": ["b2b_spb_general_main_com_mix_network", ]},
        {"descr": 'p4c_com_mix_network_bdg',
         "fltrs": ["b2b_(kazan|nn|krasnoyarsk|voronezh)_general_main_com_mix_network", ]},
        {"descr": 'reg18_com_mix_network_bdg', "fltrs": ["b2b_chelyabinsk_general_main_com_mix_network",
                                                         "b2b_ekb_general_main_com_mix_networkh",
                                                         "b2b_irkutsk_general_main_com_mix_network",
                                                         "b2b_kaliningrad_general_main_com_mix_network",
                                                         "b2b_kemerovo_general_main_com_mix_network",
                                                         "b2b_krasnodar_general_main_com_mix_network",
                                                         "b2b_novosibirsk_general_main_com_mix_network",
                                                         "b2b_omsk_general_main_com_mix_network",
                                                         "b2b_perm_general_main_com_mix_network",
                                                         "b2b_rostov_general_main_com_mix_network",
                                                         "b2b_samara_general_main_com_mix_network",
                                                         "b2b_sevastopol_general_main_com_mix_network",
                                                         "b2b_sochi_general_main_com_mix_network",
                                                         "b2b_stavropol_general_main_com_mix_network",
                                                         "b2b_tyumen_general_main_com_mix_network",
                                                         "b2b_ufa_general_main_com_mix_network",
                                                         "b2b_volgograd_general_main_com_mix_networkh",
                                                         "b2b_yalta_general_main_com_mix_network",
                                                         ]},

        {"descr": 'oth_com_mix_network_bdg', "fltrs": [
            "b2b_arhangelsk_general_main_com_mix_network",
            "b2b_astrahan_general_main_com_mix_network",
            "b2b_barnaul_general_main_com_mix_network",
            "b2b_belgorod_general_main_com_mix_network",
            "b2b_bryansk_general_main_com_mix_network",
            "b2b_cheboksary_general_main_com_mix_network",
            "b2b_habarovsk_general_main_com_mix_network",
            "b2b_ivanovo_general_main_com_mix_network",
            "b2b_izhevsk_general_main_com_mix_network",
            "b2b_kaluga_general_main_com_mix_network",
            "b2b_kirov_general_main_com_mix_network",
            "b2b_kostroma_general_main_com_mix_network",
            "b2b_kurgan_general_main_com_mix_network",
            "b2b_kursk_general_main_com_mix_network",
            "b2b_lipetsk_general_main_com_mix_network",
            "b2b_mahachkala_general_main_com_mix_network",
            "b2b_novgorod_general_main_com_mix_network",
            "b2b_orel_general_main_com_mix_network",
            "b2b_orenburg_general_main_com_mix_network",
            "b2b_penza_general_main_com_mix_network",
            "b2b_pskov_general_main_com_mix_network",
            "b2b_ryazan_general_main_com_mix_network",
            "b2b_saratov_general_main_com_mix_network",
            "b2b_smolensk_general_main_com_mix_network",
            "b2b_surgut_general_main_com_mix_network",
            "b2b_tambov_general_main_com_mix_network",
            "b2b_tomsk_general_main_com_mix_network",
            "b2b_tula_general_main_com_mix_network",
            "b2b_tver_general_main_com_mix_network",
            "b2b_ulanude_general_main_com_mix_network",
            "b2b_ulyanovsk_general_main_com_mix_network",
            "b2b_vladimir_general_main_com_mix_network",
            "b2b_vladivostok_general_main_com_mix_network",
            "b2b_yaroslavl_general_main_com_mix_network",
        ]},

        ######################################################################################
        # Пакет: competitors #################################################################
        ######################################################################################
        {"descr": 'msk_competitors_bdg', "fltrs": ["b2c_(bmo|dmo|msk)_compet_main_all_mix_search", ]},
        {"descr": 'spb_competitors_bdg', "fltrs": ["b2c_spb_compet_main_all_mix_search", ]},
        {"descr": 'p4c_competitors_bdg', "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_compet_main_all_mix_search", ]},
        {"descr": 'reg18_competitors_bdg', "fltrs": ["b2c_chelyabinsk_compet_main_all_mix_search",
                                                     "b2c_ekb_compet_main_all_mix_search",
                                                     "b2c_irkutsk_compet_main_all_mix_search",
                                                     "b2c_kaliningrad_compet_main_all_mix_search",
                                                     "b2c_kemerovo_compet_main_all_mix_search",
                                                     "b2c_krasnodar_compet_main_all_mix_search",
                                                     "b2c_novosibirsk_compet_main_all_mix_search",
                                                     "b2c_omsk_compet_main_all_mix_search",
                                                     "b2c_perm_compet_main_all_mix_search",
                                                     "b2c_rostov_compet_main_all_mix_search",
                                                     "b2c_samara_compet_main_all_mix_search",
                                                     "b2c_sevastopol_compet_main_all_mix_search",
                                                     "b2c_sochi_compet_main_all_mix_search",
                                                     "b2c_stavropol_compet_main_all_mix_search",
                                                     "b2c_tyumen_compet_main_all_mix_search",
                                                     "b2c_ufa_compet_main_all_mix_search",
                                                     "b2c_volgograd_compet_main_all_mix_search",
                                                     "b2c_yalta_compet_main_all_mix_search",
                                                     ]},
        {"descr": 'oth_competitors_bdg', "fltrs": [
            "b2c_arhangelsk_compet_main_all_mix_search",
            "b2c_astrahan_compet_main_all_mix_search",
            "b2c_barnaul_compet_main_all_mix_search",
            "b2c_belgorod_compet_main_all_mix_search",
            "b2c_bryansk_compet_main_all_mix_search",
            "b2c_cheboksary_compet_main_all_mix_search",
            "b2c_habarovsk_compet_main_all_mix_search",
            "b2c_ivanovo_compet_main_all_mix_search",
            "b2c_izhevsk_compet_main_all_mix_search",
            "b2c_kaluga_compet_main_all_mix_search",
            "b2c_kirov_compet_main_all_mix_search",
            "b2c_kostroma_compet_main_all_mix_search",
            "b2c_kurgan_compet_main_all_mix_search",
            "b2c_kursk_compet_main_all_mix_search",
            "b2c_lipetsk_compet_main_all_mix_search",
            "b2c_mahachkala_compet_main_all_mix_search",
            "b2c_novgorod_compet_main_all_mix_search",
            "b2c_orel_compet_main_all_mix_search",
            "b2c_orenburg_compet_main_all_mix_search",
            "b2c_penza_compet_main_all_mix_search",
            "b2c_pskov_compet_main_all_mix_search",
            "b2c_ryazan_compet_main_all_mix_search",
            "b2c_saratov_compet_main_all_mix_search",
            "b2c_smolensk_compet_main_all_mix_search",
            "b2c_surgut_compet_main_all_mix_search",
            "b2c_tambov_compet_main_all_mix_search",
            "b2c_tomsk_compet_main_all_mix_search",
            "b2c_tula_compet_main_all_mix_search",
            "b2c_tver_compet_main_all_mix_search",
            "b2c_ulanude_compet_main_all_mix_search",
            "b2c_ulyanovsk_compet_main_all_mix_search",
            "b2c_vladimir_compet_main_all_mix_search",
            "b2c_vladivostok_compet_main_all_mix_search",
            "b2c_yaroslavl_compet_main_all_mix_search",
        ]},

        {"descr": 'msk_brand_network_bdg', "fltrs": ["b2c_(mo|msk)_brand_main_all_mix_network", ]},
        {"descr": 'spb_brand_network_bdg', "fltrs": ["b2c_spb_brand_main_all_mix_network", ]},
        {"descr": 'p4c_brand_network_bdg',
         "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_brand_main_all_mix_network", ]},
        {"descr": 'reg18_brand_network_bdg', "fltrs": ["b2c_chelyabinsk_brand_main_all_mix_network",
                                                       "b2c_ekb_brand_main_all_mix_network",
                                                       "b2c_irkutsk_brand_main_all_mix_network",
                                                       "b2c_kaliningrad_brand_main_all_mix_network",
                                                       "b2c_kemerovo_brand_main_all_mix_network",
                                                       "b2c_krasnodar_brand_main_all_mix_network",
                                                       "b2c_novosibirsk_brand_main_all_mix_network",
                                                       "b2c_omsk_brand_main_all_mix_network",
                                                       "b2c_perm_brand_main_all_mix_network",
                                                       "b2c_rostov_brand_main_all_mix_network",
                                                       "b2c_samara_brand_main_all_mix_network",
                                                       "b2c_sevastopol_brand_main_all_mix_network",
                                                       "b2c_sochi_brand_main_all_mix_network",
                                                       "b2c_stavropol_brand_main_all_mix_network",
                                                       "b2c_tyumen_brand_main_all_mix_network",
                                                       "b2c_ufa_brand_main_all_mix_network",
                                                       "b2c_volgograd_brand_main_all_mix_network",
                                                       "b2c_yalta_brand_main_all_mix_network",
                                                       ]},
        {"descr": 'oth_brand_network_bdg', "fltrs": [
            "b2c_arhangelsk_brand_main_all_mix_network",
            "b2c_astrahan_brand_main_all_mix_network",
            "b2c_barnaul_brand_main_all_mix_network",
            "b2c_belgorod_brand_main_all_mix_network",
            "b2c_bryansk_brand_main_all_mix_network",
            "b2c_cheboksary_brand_main_all_mix_network",
            "b2c_habarovsk_brand_main_all_mix_network",
            "b2c_ivanovo_brand_main_all_mix_network",
            "b2c_izhevsk_brand_main_all_mix_network",
            "b2c_kaluga_brand_main_all_mix_network",
            "b2c_kirov_brand_main_all_mix_network",
            "b2c_kostroma_brand_main_all_mix_network",
            "b2c_kurgan_brand_main_all_mix_network",
            "b2c_kursk_brand_main_all_mix_network",
            "b2c_lipetsk_brand_main_all_mix_network",
            "b2c_mahachkala_brand_main_all_mix_network",
            "b2c_novgorod_brand_main_all_mix_network",
            "b2c_orel_brand_main_all_mix_network",
            "b2c_orenburg_brand_main_all_mix_network",
            "b2c_penza_brand_main_all_mix_network",
            "b2c_pskov_brand_main_all_mix_network",
            "b2c_ryazan_brand_main_all_mix_network",
            "b2c_saratov_brand_main_all_mix_network",
            "b2c_smolensk_brand_main_all_mix_network",
            "b2c_surgut_brand_main_all_mix_network",
            "b2c_tambov_brand_main_all_mix_network",
            "b2c_tomsk_brand_main_all_mix_network",
            "b2c_tula_brand_main_all_mix_network",
            "b2c_tver_brand_main_all_mix_network",
            "b2c_ulanude_brand_main_all_mix_network",
            "b2c_ulyanovsk_brand_main_all_mix_network",
            "b2c_vladimir_brand_main_all_mix_network",
            "b2c_vladivostok_brand_main_all_mix_network",
            "b2c_yaroslavl_brand_main_all_mix_network",
        ]},

        ######################################################################################
        # Пакет: main_nov ####################################################################
        ######################################################################################
        {"descr": 'msk_general_main_nov_bdg', "fltrs": ["b2c_(bmo|dmo|msk)_general_(main|geo)_nov_mix_search", ]},
        {"descr": 'spb_general_main_nov_bdg', "fltrs": ["b2c_spb_general_main_nov_mix_search", ]},
        {"descr": 'p4c_general_main_nov_bdg',
         "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_general_main_nov_mix_search", ]},
        {"descr": 'reg18_general_main_nov_bdg', "fltrs": ["b2c_chelyabinsk_general_main_nov_mix_search",
                                                          "b2c_ekb_general_main_nov_mix_search",
                                                          "b2c_irkutsk_general_main_nov_mix_search",
                                                          "b2c_kaliningrad_general_main_nov_mix_search",
                                                          "b2c_kemerovo_general_main_nov_mix_search",
                                                          "b2c_krasnodar_general_main_nov_mix_search",
                                                          "b2c_novosibirsk_general_main_nov_mix_search",
                                                          "b2c_omsk_general_main_nov_mix_search",
                                                          "b2c_perm_general_main_nov_mix_search",
                                                          "b2c_rostov_general_main_nov_mix_search",
                                                          "b2c_samara_general_main_nov_mix_search",
                                                          "b2c_sevastopol_general_main_nov_mix_search",
                                                          "b2c_sochi_general_main_nov_mix_search",
                                                          "b2c_stavropol_general_main_nov_mix_search",
                                                          "b2c_tyumen_general_main_nov_mix_search",
                                                          "b2c_ufa_general_main_nov_mix_search",
                                                          "b2c_volgograd_general_main_nov_mix_search",
                                                          "b2c_yalta_general_main_nov_mix_search",
                                                          ]},
        {"descr": 'oth_general_main_nov_bdg', "fltrs": [
            "b2c_arhangelsk_general_main_nov_mix_search",
            "b2c_astrahan_general_main_nov_mix_search",
            "b2c_barnaul_general_main_nov_mix_search",
            "b2c_belgorod_general_main_nov_mix_search",
            "b2c_bryansk_general_main_nov_mix_search",
            "b2c_cheboksary_general_main_nov_mix_search",
            "b2c_habarovsk_general_main_nov_mix_search",
            "b2c_ivanovo_general_main_nov_mix_search",
            "b2c_izhevsk_general_main_nov_mix_search",
            "b2c_kaluga_general_main_nov_mix_search",
            "b2c_kirov_general_main_nov_mix_search",
            "b2c_kostroma_general_main_nov_mix_search",
            "b2c_kurgan_general_main_nov_mix_search",
            "b2c_kursk_general_main_nov_mix_search",
            "b2c_lipetsk_general_main_nov_mix_search",
            "b2c_mahachkala_general_main_nov_mix_search",
            "b2c_novgorod_general_main_nov_mix_search",
            "b2c_orel_general_main_nov_mix_search",
            "b2c_orenburg_general_main_nov_mix_search",
            "b2c_penza_general_main_nov_mix_search",
            "b2c_pskov_general_main_nov_mix_search",
            "b2c_ryazan_general_main_nov_mix_search",
            "b2c_saratov_general_main_nov_mix_search",
            "b2c_smolensk_general_main_nov_mix_search",
            "b2c_surgut_general_main_nov_mix_search",
            "b2c_tambov_general_main_nov_mix_search",
            "b2c_tomsk_general_main_nov_mix_search",
            "b2c_tula_general_main_nov_mix_search",
            "b2c_tver_general_main_nov_mix_search",
            "b2c_ulanude_general_main_nov_mix_search",
            "b2c_ulyanovsk_general_main_nov_mix_search",
            "b2c_vladimir_general_main_nov_mix_search",
            "b2c_vladivostok_general_main_nov_mix_search",
            "b2c_yaroslavl_general_main_nov_mix_search",
        ]},

        {"descr": 'msk_general_nov_network_bdg', "fltrs": ["b2c_(mo|msk)_general_main_nov_mix_network", ]},
        {"descr": 'spb_general_nov_network_bdg', "fltrs": ["b2c_spb_general_main_nov_mix_network", ]},
        {"descr": 'p4c_general_nov_network_bdg',
         "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_general_main_nov_mix_network", ]},
        {"descr": 'reg18_general_nov_network_bdg', "fltrs": ["b2c_chelyabinsk_general_main_nov_mix_network",
                                                             "b2c_ekb_general_main_nov_mix_network",
                                                             "b2c_irkutsk_general_main_nov_mix_network",
                                                             "b2c_kaliningrad_general_main_nov_mix_network",
                                                             "b2c_kemerovo_general_main_nov_mix_network",
                                                             "b2c_krasnodar_general_main_nov_mix_network",
                                                             "b2c_novosibirsk_general_main_nov_mix_network",
                                                             "b2c_omsk_general_main_nov_mix_network",
                                                             "b2c_perm_general_main_nov_mix_network",
                                                             "b2c_rostov_general_main_nov_mix_network",
                                                             "b2c_samara_general_main_nov_mix_network",
                                                             "b2c_sevastopol_general_main_nov_mix_network",
                                                             "b2c_sochi_general_main_nov_mix_network",
                                                             "b2c_stavropol_general_main_nov_mix_network",
                                                             "b2c_tyumen_general_main_nov_mix_network",
                                                             "b2c_ufa_general_main_nov_mix_network",
                                                             "b2c_volgograd_general_main_nov_mix_network",
                                                             "b2c_yalta_general_main_nov_mix_network",
                                                             ]},
        {"descr": 'oth_general_nov_network_bdg', "fltrs": [
            "b2c_arhangelsk_general_main_nov_mix_network",
            "b2c_astrahan_general_main_nov_mix_network",
            "b2c_barnaul_general_main_nov_mix_network",
            "b2c_belgorod_general_main_nov_mix_network",
            "b2c_bryansk_general_main_nov_mix_network",
            "b2c_cheboksary_general_main_nov_mix_network",
            "b2c_habarovsk_general_main_nov_mix_network",
            "b2c_ivanovo_general_main_nov_mix_network",
            "b2c_izhevsk_general_main_nov_mix_network",
            "b2c_kaluga_general_main_nov_mix_network",
            "b2c_kirov_general_main_nov_mix_network",
            "b2c_kostroma_general_main_nov_mix_network",
            "b2c_kurgan_general_main_nov_mix_network",
            "b2c_kursk_general_main_nov_mix_network",
            "b2c_lipetsk_general_main_nov_mix_network",
            "b2c_mahachkala_general_main_nov_mix_network",
            "b2c_novgorod_general_main_nov_mix_network",
            "b2c_orel_general_main_nov_mix_network",
            "b2c_orenburg_general_main_nov_mix_network",
            "b2c_penza_general_main_nov_mix_network",
            "b2c_pskov_general_main_nov_mix_network",
            "b2c_ryazan_general_main_nov_mix_network",
            "b2c_saratov_general_main_nov_mix_network",
            "b2c_smolensk_general_main_nov_mix_network",
            "b2c_surgut_general_main_nov_mix_network",
            "b2c_tambov_general_main_nov_mix_network",
            "b2c_tomsk_general_main_nov_mix_network",
            "b2c_tula_general_main_nov_mix_network",
            "b2c_tver_general_main_nov_mix_network",
            "b2c_ulanude_general_main_nov_mix_network",
            "b2c_ulyanovsk_general_main_nov_mix_network",
            "b2c_vladimir_general_main_nov_mix_network",
            "b2c_vladivostok_general_main_nov_mix_network",
            "b2c_yaroslavl_general_main_nov_mix_network",
        ]},

        ######################################################################################
        # Пакет: pysea #######################################################################
        ######################################################################################
        {"descr": 'msk_jk_pys_nov_mix_search_bdg', "fltrs": ["b2c_(mo|msk)_jk_pys_nov_mix_search", ]},
        {"descr": 'spb_jk_pys_nov_mix_search_bdg', "fltrs": ["b2c_spb_jk_pys_nov_mix_search", ]},
        {"descr": 'p4c_jk_pys_nov_mix_search_bdg',
         "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_jk_pys_nov_mix_search", ]},
        {"descr": 'reg18_jk_pys_nov_mix_search_bdg', "fltrs": ["b2c_chelyabinsk_jk_pys_nov_mix_search",
                                                               "b2c_ekb_jk_pys_nov_mix_search",
                                                               "b2c_irkutsk_jk_pys_nov_mix_search",
                                                               "b2c_kaliningrad_jk_pys_nov_mix_search",
                                                               "b2c_kemerovo_jk_pys_nov_mix_search",
                                                               "b2c_krasnodar_jk_pys_nov_mix_search",
                                                               "b2c_novosibirsk_jk_pys_nov_mix_search",
                                                               "b2c_omsk_jk_pys_nov_mix_search",
                                                               "b2c_perm_jk_pys_nov_mix_search",
                                                               "b2c_rostov_jk_pys_nov_mix_search",
                                                               "b2c_samara_jk_pys_nov_mix_search",
                                                               "b2c_sevastopol_jk_pys_nov_mix_search",
                                                               "b2c_sochi_jk_pys_nov_mix_search",
                                                               "b2c_stavropol_jk_pys_nov_mix_search",
                                                               "b2c_tyumen_jk_pys_nov_mix_search",
                                                               "b2c_ufa_jk_pys_nov_mix_search",
                                                               "b2c_volgograd_jk_pys_nov_mix_search",
                                                               "b2c_yalta_jk_pys_nov_mix_search",
                                                               ]},
        {"descr": 'oth_jk_pys_nov_mix_search_bdg', "fltrs": [
            "b2c_arhangelsk_jk_pys_nov_mix_search",
            "b2c_astrahan_jk_pys_nov_mix_search",
            "b2c_barnaul_jk_pys_nov_mix_search",
            "b2c_belgorod_jk_pys_nov_mix_search",
            "b2c_bryansk_jk_pys_nov_mix_search",
            "b2c_cheboksary_jk_pys_nov_mix_search",
            "b2c_habarovsk_jk_pys_nov_mix_search",
            "b2c_ivanovo_jk_pys_nov_mix_search",
            "b2c_izhevsk_jk_pys_nov_mix_search",
            "b2c_kaluga_jk_pys_nov_mix_search",
            "b2c_kirov_jk_pys_nov_mix_search",
            "b2c_kostroma_jk_pys_nov_mix_search",
            "b2c_kurgan_jk_pys_nov_mix_search",
            "b2c_kursk_jk_pys_nov_mix_search",
            "b2c_lipetsk_jk_pys_nov_mix_search",
            "b2c_mahachkala_jk_pys_nov_mix_search",
            "b2c_novgorod_jk_pys_nov_mix_search",
            "b2c_orel_jk_pys_nov_mix_search",
            "b2c_orenburg_jk_pys_nov_mix_search",
            "b2c_penza_jk_pys_nov_mix_search",
            "b2c_pskov_jk_pys_nov_mix_search",
            "b2c_ryazan_jk_pys_nov_mix_search",
            "b2c_saratov_jk_pys_nov_mix_search",
            "b2c_smolensk_jk_pys_nov_mix_search",
            "b2c_surgut_jk_pys_nov_mix_search",
            "b2c_tambov_jk_pys_nov_mix_search",
            "b2c_tomsk_jk_pys_nov_mix_search",
            "b2c_tula_jk_pys_nov_mix_search",
            "b2c_tver_jk_pys_nov_mix_search",
            "b2c_ulanude_jk_pys_nov_mix_search",
            "b2c_ulyanovsk_jk_pys_nov_mix_search",
            "b2c_vladimir_jk_pys_nov_mix_search",
            "b2c_vladivostok_jk_pys_nov_mix_search",
            "b2c_yaroslavl_jk_pys_nov_mix_search",
        ]},

        ######################################################################################
        # Пакет: rentsec #######################################################################
        ######################################################################################
        {"descr": 'msk_rentsec_mix_search_bdg',
         "fltrs": ["b2c_(dmo|bmo|msk)_general_(null|geo|subreg)_rentsec_mix_search", ]},
        {"descr": 'spb_rentsec_mix_search_bdg', "fltrs": ["b2c_spb_general_(null|subreg)_rentsec_mix_search", ]},
        {"descr": 'p4c_rentsec_mix_search_bdg',
         "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_general_null_rentsec_mix_search", ]},
        {"descr": 'reg18_rentsec_mix_search_bdg', "fltrs": ["b2c_chelyabinsk_general_null_rentsec_mix_search",
                                                            "b2c_ekb_general_null_rentsec_mix_search",
                                                            "b2c_irkutsk_general_null_rentsec_mix_search",
                                                            "b2c_kaliningrad_general_null_rentsec_mix_search",
                                                            "b2c_kemerovo_general_null_rentsec_mix_search",
                                                            "b2c_krasnodar_general_null_rentsec_mix_search",
                                                            "b2c_novosibirsk_general_null_rentsec_mix_search",
                                                            "b2c_omsk_general_null_rentsec_mix_search",
                                                            "b2c_perm_general_null_rentsec_mix_search",
                                                            "b2c_rostov_general_null_rentsec_mix_search",
                                                            "b2c_samara_general_null_rentsec_mix_search",
                                                            "b2c_sevastopol_general_null_rentsec_mix_search",
                                                            "b2c_sochi_general_null_rentsec_mix_search",
                                                            "b2c_stavropol_general_null_rentsec_mix_search",
                                                            "b2c_tyumen_general_null_rentsec_mix_search",
                                                            "b2c_ufa_general_null_rentsec_mix_search",
                                                            "b2c_volgograd_general_null_rentsec_mix_search",
                                                            "b2c_yalta_general_null_rentsec_mix_search",
                                                            ]},
        {"descr": 'oth_rentsec_mix_search_bdg', "fltrs": [
            "b2c_arhangelsk_general_null_rentsec_mix_search",
            "b2c_astrahan_general_null_rentsec_mix_search",
            "b2c_barnaul_general_null_rentsec_mix_search",
            "b2c_belgorod_general_null_rentsec_mix_search",
            "b2c_bryansk_general_null_rentsec_mix_search",
            "b2c_cheboksary_general_null_rentsec_mix_search",
            "b2c_habarovsk_general_null_rentsec_mix_search",
            "b2c_ivanovo_general_null_rentsec_mix_search",
            "b2c_izhevsk_general_null_rentsec_mix_search",
            "b2c_kaluga_general_null_rentsec_mix_search",
            "b2c_kirov_general_null_rentsec_mix_search",
            "b2c_kostroma_general_null_rentsec_mix_search",
            "b2c_kurgan_general_null_rentsec_mix_search",
            "b2c_kursk_general_null_rentsec_mix_search",
            "b2c_lipetsk_general_null_rentsec_mix_search",
            "b2c_mahachkala_general_null_rentsec_mix_search",
            "b2c_novgorod_general_null_rentsec_mix_search",
            "b2c_orel_general_null_rentsec_mix_search",
            "b2c_orenburg_general_null_rentsec_mix_search",
            "b2c_penza_general_null_rentsec_mix_search",
            "b2c_pskov_general_null_rentsec_mix_search",
            "b2c_ryazan_general_null_rentsec_mix_search",
            "b2c_saratov_general_null_rentsec_mix_search",
            "b2c_smolensk_general_null_rentsec_mix_search",
            "b2c_surgut_general_null_rentsec_mix_search",
            "b2c_tambov_general_null_rentsec_mix_search",
            "b2c_tomsk_general_null_rentsec_mix_search",
            "b2c_tula_general_null_rentsec_mix_search",
            "b2c_tver_general_null_rentsec_mix_search",
            "b2c_ulanude_general_null_rentsec_mix_search",
            "b2c_ulyanovsk_general_null_rentsec_mix_search",
            "b2c_vladimir_general_null_rentsec_mix_search",
            "b2c_vladivostok_general_null_rentsec_mix_search",
            "b2c_yaroslavl_general_null_rentsec_mix_search",
        ]},

        {"descr": 'msk_dsa_rentsec_mix_search_bdg', "fltrs": ["b2c_(mo|msk)_dsa_subreg_rentsec_mix_search", ]},
        {"descr": 'spb_dsa_rentsec_mix_search_bdg', "fltrs": ["b2c_spb_dsa_subreg_rentsec_mix_search", ]},
        {"descr": 'oth_dsa_rentsec_mix_search_bdg', "fltrs": ["b2c_krasnodar_dsa_subreg_rentsec_mix_search", ]},

        {"descr": 'msk_rentsec_mix_network_bdg', "fltrs": ["b2c_(mo|msk)_general_main_rentsec_mix_network", ]},
        {"descr": 'spb_rentsec_mix_network_bdg', "fltrs": ["b2c_spb_general_main_rentsec_mix_network", ]},
        {"descr": 'p4c_rentsec_mix_network_bdg',
         "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_general_main_rentsec_mix_network", ]},
        {"descr": 'reg18_rentsec_mix_network_bdg', "fltrs": ["b2c_chelyabinsk_general_main_rentsec_mix_network",
                                                             "b2c_ekb_general_main_rentsec_mix_network",
                                                             "b2c_irkutsk_general_main_rentsec_mix_network",
                                                             "b2c_kaliningrad_general_main_rentsec_mix_network",
                                                             "b2c_kemerovo_general_main_rentsec_mix_network",
                                                             "b2c_krasnodar_general_main_rentsec_mix_network",
                                                             "b2c_novosibirsk_general_main_rentsec_mix_network",
                                                             "b2c_omsk_general_main_rentsec_mix_network",
                                                             "b2c_perm_general_main_rentsec_mix_network",
                                                             "b2c_rostov_general_main_rentsec_mix_network",
                                                             "b2c_samara_general_main_rentsec_mix_network",
                                                             "b2c_sevastopol_general_main_rentsec_mix_network",
                                                             "b2c_sochi_general_main_rentsec_mix_network",
                                                             "b2c_stavropol_general_main_rentsec_mix_network",
                                                             "b2c_tyumen_general_main_rentsec_mix_network",
                                                             "b2c_ufa_general_main_rentsec_mix_network",
                                                             "b2c_volgograd_general_main_rentsec_mix_network",
                                                             "b2c_yalta_general_main_rentsec_mix_network",
                                                             ]},
        {"descr": 'oth_rentsec_mix_network_bdg', "fltrs": [
            "b2c_arhangelsk_general_main_rentsec_mix_network",
            "b2c_astrahan_general_main_rentsec_mix_network",
            "b2c_barnaul_general_main_rentsec_mix_network",
            "b2c_belgorod_general_main_rentsec_mix_network",
            "b2c_bryansk_general_main_rentsec_mix_network",
            "b2c_cheboksary_general_main_rentsec_mix_network",
            "b2c_habarovsk_general_main_rentsec_mix_network",
            "b2c_ivanovo_general_main_rentsec_mix_network",
            "b2c_izhevsk_general_main_rentsec_mix_network",
            "b2c_kaluga_general_main_rentsec_mix_network",
            "b2c_kirov_general_main_rentsec_mix_network",
            "b2c_kostroma_general_main_rentsec_mix_network",
            "b2c_kurgan_general_main_rentsec_mix_network",
            "b2c_kursk_general_main_rentsec_mix_network",
            "b2c_lipetsk_general_main_rentsec_mix_network",
            "b2c_mahachkala_general_main_rentsec_mix_network",
            "b2c_novgorod_general_main_rentsec_mix_network",
            "b2c_orel_general_main_rentsec_mix_network",
            "b2c_orenburg_general_main_rentsec_mix_network",
            "b2c_penza_general_main_rentsec_mix_network",
            "b2c_pskov_general_main_rentsec_mix_network",
            "b2c_ryazan_general_main_rentsec_mix_network",
            "b2c_saratov_general_main_rentsec_mix_network",
            "b2c_smolensk_general_main_rentsec_mix_network",
            "b2c_surgut_general_main_rentsec_mix_network",
            "b2c_tambov_general_main_rentsec_mix_network",
            "b2c_tomsk_general_main_rentsec_mix_network",
            "b2c_tula_general_main_rentsec_mix_network",
            "b2c_tver_general_main_rentsec_mix_network",
            "b2c_ulanude_general_main_rentsec_mix_network",
            "b2c_ulyanovsk_general_main_rentsec_mix_network",
            "b2c_vladimir_general_main_rentsec_mix_network",
            "b2c_vladivostok_general_main_rentsec_mix_network",
            "b2c_yaroslavl_general_main_rentsec_mix_network",
        ]},

        ######################################################################################
        # Пакет: salesec #######################################################################
        ######################################################################################
        {"descr": 'msk_salesec_mix_search_bdg',
         "fltrs": ["b2c_(bmo|dmo|msk)_general_(null|geo|subreg)_salesec_mix_search", ]},
        {"descr": 'spb_salesec_mix_search_bdg', "fltrs": ["b2c_spb_general_null_salesec_mix_search", ]},
        {"descr": 'p4c_salesec_mix_search_bdg',
         "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_general_null_salesec_mix_search", ]},
        {"descr": 'reg18_salesec_mix_search_bdg', "fltrs": ["b2c_chelyabinsk_general_null_salesec_mix_search",
                                                            "b2c_ekb_general_null_salesec_mix_search",
                                                            "b2c_irkutsk_general_null_salesec_mix_search",
                                                            "b2c_kaliningrad_general_null_salesec_mix_search",
                                                            "b2c_kemerovo_general_null_salesec_mix_search",
                                                            "b2c_krasnodar_general_null_salesec_mix_search",
                                                            "b2c_novosibirsk_general_null_salesec_mix_search",
                                                            "b2c_omsk_general_null_salesec_mix_search",
                                                            "b2c_perm_general_null_salesec_mix_search",
                                                            "b2c_rostov_general_null_salesec_mix_search",
                                                            "b2c_samara_general_null_salesec_mix_search",
                                                            "b2c_sevastopol_general_null_salesec_mix_search",
                                                            "b2c_sochi_general_null_salesec_mix_search",
                                                            "b2c_stavropol_general_null_salesec_mix_search",
                                                            "b2c_tyumen_general_null_salesec_mix_search",
                                                            "b2c_ufa_general_null_salesec_mix_search",
                                                            "b2c_volgograd_general_null_salesec_mix_search",
                                                            "b2c_yalta_general_null_salesec_mix_search",
                                                            ]},
        {"descr": 'oth_salesec_mix_search_bdg', "fltrs": [
            "b2c_arhangelsk_general_null_salesec_mix_search",
            "b2c_astrahan_general_null_salesec_mix_search",
            "b2c_barnaul_general_null_salesec_mix_search",
            "b2c_belgorod_general_null_salesec_mix_search",
            "b2c_bryansk_general_null_salesec_mix_search",
            "b2c_cheboksary_general_null_salesec_mix_search",
            "b2c_habarovsk_general_null_salesec_mix_search",
            "b2c_ivanovo_general_null_salesec_mix_search",
            "b2c_izhevsk_general_null_salesec_mix_search",
            "b2c_kaluga_general_null_salesec_mix_search",
            "b2c_kirov_general_null_salesec_mix_search",
            "b2c_kostroma_general_null_salesec_mix_search",
            "b2c_kurgan_general_null_salesec_mix_search",
            "b2c_kursk_general_null_salesec_mix_search",
            "b2c_lipetsk_general_null_salesec_mix_search",
            "b2c_mahachkala_general_null_salesec_mix_search",
            "b2c_novgorod_general_null_salesec_mix_search",
            "b2c_orel_general_null_salesec_mix_search",
            "b2c_orenburg_general_null_salesec_mix_search",
            "b2c_penza_general_null_salesec_mix_search",
            "b2c_pskov_general_null_salesec_mix_search",
            "b2c_ryazan_general_null_salesec_mix_search",
            "b2c_saratov_general_null_salesec_mix_search",
            "b2c_smolensk_general_null_salesec_mix_search",
            "b2c_surgut_general_null_salesec_mix_search",
            "b2c_tambov_general_null_salesec_mix_search",
            "b2c_tomsk_general_null_salesec_mix_search",
            "b2c_tula_general_null_salesec_mix_search",
            "b2c_tver_general_null_salesec_mix_search",
            "b2c_ulanude_general_null_salesec_mix_search",
            "b2c_ulyanovsk_general_null_salesec_mix_search",
            "b2c_vladimir_general_null_salesec_mix_search",
            "b2c_vladivostok_general_null_salesec_mix_search",
            "b2c_yaroslavl_general_null_salesec_mix_search",
        ]},

        {"descr": 'msk_dsa_salesec_mix_search_bdg', "fltrs": ["b2c_(mo|msk)_dsa_subreg_salesec_mix_search", ]},
        {"descr": 'spb_dsa_salesec_mix_search_bdg', "fltrs": ["b2c_spb_dsa_subreg_salesec_mix_search", ]},
        {"descr": 'oth_dsa_salesec_mix_search_bdg', "fltrs": ["b2c_krasnodar_dsa_subreg_salesec_mix_search", ]},

        {"descr": 'msk_salesec_mix_network_bdg', "fltrs": ["b2c_(mo|msk)_general_main_salesec_mix_network", ]},
        {"descr": 'spb_salesec_mix_network_bdg', "fltrs": ["b2c_spb_general_main_salesec_mix_network", ]},
        {"descr": 'p4c_salesec_mix_network_bdg',
         "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_general_main_salesec_mix_network", ]},
        {"descr": 'reg18_salesec_mix_network_bdg', "fltrs": ["b2c_chelyabinsk_general_main_salesec_mix_network",
                                                             "b2c_ekb_general_main_salesec_mix_network",
                                                             "b2c_irkutsk_general_main_salesec_mix_network",
                                                             "b2c_kaliningrad_general_main_salesec_mix_network",
                                                             "b2c_kemerovo_general_main_salesec_mix_network",
                                                             "b2c_krasnodar_general_main_salesec_mix_network",
                                                             "b2c_novosibirsk_general_main_salesec_mix_network",
                                                             "b2c_omsk_general_main_salesec_mix_network",
                                                             "b2c_perm_general_main_salesec_mix_network",
                                                             "b2c_rostov_general_main_salesec_mix_network",
                                                             "b2c_samara_general_main_salesec_mix_network",
                                                             "b2c_sevastopol_general_main_salesec_mix_network",
                                                             "b2c_sochi_general_main_salesec_mix_network",
                                                             "b2c_stavropol_general_main_salesec_mix_network",
                                                             "b2c_tyumen_general_main_salesec_mix_network",
                                                             "b2c_ufa_general_main_salesec_mix_network",
                                                             "b2c_volgograd_general_main_salesec_mix_network",
                                                             "b2c_yalta_general_main_salesec_mix_network",
                                                             ]},
        {"descr": 'oth_salesec_mix_network_bdg', "fltrs": [
            "b2c_arhangelsk_general_main_salesec_mix_network",
            "b2c_astrahan_general_main_salesec_mix_network",
            "b2c_barnaul_general_main_salesec_mix_network",
            "b2c_belgorod_general_main_salesec_mix_network",
            "b2c_bryansk_general_main_salesec_mix_network",
            "b2c_cheboksary_general_main_salesec_mix_network",
            "b2c_habarovsk_general_main_salesec_mix_network",
            "b2c_ivanovo_general_main_salesec_mix_network",
            "b2c_izhevsk_general_main_salesec_mix_network",
            "b2c_kaluga_general_main_salesec_mix_network",
            "b2c_kirov_general_main_salesec_mix_network",
            "b2c_kostroma_general_main_salesec_mix_network",
            "b2c_kurgan_general_main_salesec_mix_network",
            "b2c_kursk_general_main_salesec_mix_network",
            "b2c_lipetsk_general_main_salesec_mix_network",
            "b2c_mahachkala_general_main_salesec_mix_network",
            "b2c_novgorod_general_main_salesec_mix_network",
            "b2c_orel_general_main_salesec_mix_network",
            "b2c_orenburg_general_main_salesec_mix_network",
            "b2c_penza_general_main_salesec_mix_network",
            "b2c_pskov_general_main_salesec_mix_network",
            "b2c_ryazan_general_main_salesec_mix_network",
            "b2c_saratov_general_main_salesec_mix_network",
            "b2c_smolensk_general_main_salesec_mix_network",
            "b2c_surgut_general_main_salesec_mix_network",
            "b2c_tambov_general_main_salesec_mix_network",
            "b2c_tomsk_general_main_salesec_mix_network",
            "b2c_tula_general_main_salesec_mix_network",
            "b2c_tver_general_main_salesec_mix_network",
            "b2c_ulanude_general_main_salesec_mix_network",
            "b2c_ulyanovsk_general_main_salesec_mix_network",
            "b2c_vladimir_general_main_salesec_mix_network",
            "b2c_vladivostok_general_main_salesec_mix_network",
            "b2c_yaroslavl_general_main_salesec_mix_network",
        ]},

        ######################################################################################
        # Пакет: sub #########################################################################
        ######################################################################################
        {"descr": 'msk_sub_mix_search_bdg', "fltrs": ["b2c_(bmo|dmo|msk)_general_(null|geo)_sub_mix_search", ]},
        {"descr": 'spb_sub_mix_search_bdg', "fltrs": ["b2c_spb_general_null_sub_mix_search", ]},
        {"descr": 'p4c_sub_mix_search_bdg',
         "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_general_null_sub_mix_search", ]},
        {"descr": 'reg18_sub_mix_search_bdg', "fltrs": ["b2c_chelyabinsk_general_null_sub_mix_search",
                                                        "b2c_ekb_general_null_sub_mix_search",
                                                        "b2c_irkutsk_general_null_sub_mix_search",
                                                        "b2c_kaliningrad_general_null_sub_mix_search",
                                                        "b2c_kemerovo_general_null_sub_mix_search",
                                                        "b2c_krasnodar_general_null_sub_mix_search",
                                                        "b2c_novosibirsk_general_null_sub_mix_search",
                                                        "b2c_omsk_general_null_sub_mix_search",
                                                        "b2c_perm_general_null_sub_mix_search",
                                                        "b2c_rostov_general_null_sub_mix_search",
                                                        "b2c_samara_general_null_sub_mix_search",
                                                        "b2c_sevastopol_general_null_sub_mix_search",
                                                        "b2c_sochi_general_null_sub_mix_search",
                                                        "b2c_stavropol_general_null_sub_mix_search",
                                                        "b2c_tyumen_general_null_sub_mix_search",
                                                        "b2c_ufa_general_null_sub_mix_search",
                                                        "b2c_volgograd_general_null_sub_mix_search",
                                                        "b2c_yalta_general_null_sub_mix_search",
                                                        ]},
        {"descr": 'oth_sub_mix_search_bdg', "fltrs": [
            "b2c_arhangelsk_general_null_sub_mix_search",
            "b2c_astrahan_general_null_sub_mix_search",
            "b2c_barnaul_general_null_sub_mix_search",
            "b2c_belgorod_general_null_sub_mix_search",
            "b2c_bryansk_general_null_sub_mix_search",
            "b2c_cheboksary_general_null_sub_mix_search",
            "b2c_habarovsk_general_null_sub_mix_search",
            "b2c_ivanovo_general_null_sub_mix_search",
            "b2c_izhevsk_general_null_sub_mix_search",
            "b2c_kaluga_general_null_sub_mix_search",
            "b2c_kirov_general_null_sub_mix_search",
            "b2c_kostroma_general_null_sub_mix_search",
            "b2c_kurgan_general_null_sub_mix_search",
            "b2c_kursk_general_null_sub_mix_search",
            "b2c_lipetsk_general_null_sub_mix_search",
            "b2c_mahachkala_general_null_sub_mix_search",
            "b2c_novgorod_general_null_sub_mix_search",
            "b2c_orel_general_null_sub_mix_search",
            "b2c_orenburg_general_null_sub_mix_search",
            "b2c_penza_general_null_sub_mix_search",
            "b2c_pskov_general_null_sub_mix_search",
            "b2c_ryazan_general_null_sub_mix_search",
            "b2c_saratov_general_null_sub_mix_search",
            "b2c_smolensk_general_null_sub_mix_search",
            "b2c_surgut_general_null_sub_mix_search",
            "b2c_tambov_general_null_sub_mix_search",
            "b2c_tomsk_general_null_sub_mix_search",
            "b2c_tula_general_null_sub_mix_search",
            "b2c_tver_general_null_sub_mix_search",
            "b2c_ulanude_general_null_sub_mix_search",
            "b2c_ulyanovsk_general_null_sub_mix_search",
            "b2c_vladimir_general_null_sub_mix_search",
            "b2c_vladivostok_general_null_sub_mix_search",
            "b2c_yaroslavl_general_null_sub_mix_search",
        ]},

        {"descr": 'msk_dsa_sub_mix_search_bdg', "fltrs": ["b2c_(mo|msk)_dsa_subreg_sub_mix_search", ]},
        {"descr": 'spb_dsa_sub_mix_search_bdg', "fltrs": ["b2c_spb_dsa_subreg_sub_mix_search", ]},
        {"descr": 'msk_sub_mix_network_bdg', "fltrs": ["b2c_(mo|msk)_general_main_sub_mix_network", ]},
        {"descr": 'spb_sub_mix_network_bdg', "fltrs": ["b2c_spb_general_main_sub_mix_network", ]},
        {"descr": 'p4c_sub_mix_network_bdg',
         "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_general_main_sub_mix_network", ]},
        {"descr": 'reg18_sub_mix_network_bdg', "fltrs": ["b2c_chelyabinsk_general_main_sub_mix_network",
                                                         "b2c_ekb_general_main_sub_mix_network",
                                                         "b2c_irkutsk_general_main_sub_mix_network",
                                                         "b2c_kaliningrad_general_main_sub_mix_network",
                                                         "b2c_kemerovo_general_main_sub_mix_network",
                                                         "b2c_krasnodar_general_main_sub_mix_network",
                                                         "b2c_novosibirsk_general_main_sub_mix_network",
                                                         "b2c_omsk_general_main_sub_mix_network",
                                                         "b2c_perm_general_main_sub_mix_network",
                                                         "b2c_rostov_general_main_sub_mix_network",
                                                         "b2c_samara_general_main_sub_mix_network",
                                                         "b2c_sevastopol_general_main_sub_mix_network",
                                                         "b2c_sochi_general_main_sub_mix_network",
                                                         "b2c_stavropol_general_main_sub_mix_network",
                                                         "b2c_tyumen_general_main_sub_mix_network",
                                                         "b2c_ufa_general_main_sub_mix_network",
                                                         "b2c_volgograd_general_main_sub_mix_network",
                                                         "b2c_yalta_general_main_sub_mix_network", ]},
        {"descr": 'oth_sub_mix_network_bdg', "fltrs": [
            "b2c_arhangelsk_general_main_sub_mix_network",
            "b2c_astrahan_general_main_sub_mix_network",
            "b2c_barnaul_general_main_sub_mix_network",
            "b2c_belgorod_general_main_sub_mix_network",
            "b2c_bryansk_general_main_sub_mix_network",
            "b2c_cheboksary_general_main_sub_mix_network",
            "b2c_habarovsk_general_main_sub_mix_network",
            "b2c_ivanovo_general_main_sub_mix_network",
            "b2c_izhevsk_general_main_sub_mix_network",
            "b2c_kaluga_general_main_sub_mix_network",
            "b2c_kirov_general_main_sub_mix_network",
            "b2c_kostroma_general_main_sub_mix_network",
            "b2c_kurgan_general_main_sub_mix_network",
            "b2c_kursk_general_main_sub_mix_network",
            "b2c_lipetsk_general_main_sub_mix_network",
            "b2c_mahachkala_general_main_sub_mix_network",
            "b2c_novgorod_general_main_sub_mix_network",
            "b2c_orel_general_main_sub_mix_network",
            "b2c_orenburg_general_main_sub_mix_network",
            "b2c_penza_general_main_sub_mix_network",
            "b2c_pskov_general_main_sub_mix_network",
            "b2c_ryazan_general_main_sub_mix_network",
            "b2c_saratov_general_main_sub_mix_network",
            "b2c_smolensk_general_main_sub_mix_network",
            "b2c_surgut_general_main_sub_mix_network",
            "b2c_tambov_general_main_sub_mix_network",
            "b2c_tomsk_general_main_sub_mix_network",
            "b2c_tula_general_main_sub_mix_network",
            "b2c_tver_general_main_sub_mix_network",
            "b2c_ulanude_general_main_sub_mix_network",
            "b2c_ulyanovsk_general_main_sub_mix_network",
            "b2c_vladimir_general_main_sub_mix_network",
            "b2c_vladivostok_general_main_sub_mix_network",
            "b2c_yaroslavl_general_main_sub_mix_network",
        ]},
        ######################################################################################
        # Пакет: DRTG NOV #########################################################################
        ######################################################################################
        {"descr": 'msk_drtg_jk_nov_bdg', "fltrs": ["b2c_(mo|msk)_drtg_jk_nov_mix_network", ]},
        {"descr": 'spb_drtg_jk_nov_bdg', "fltrs": ["b2c_spb_drtg_jk_nov_mix_network", ]},
        {"descr": 'p4c_drtg_jk_nov_bdg', "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_drtg_jk_nov_mix_network", ]},
        {"descr": 'reg18_drtg_jk_nov_bdg', "fltrs": ["b2c_chelyabinsk_drtg_jk_nov_mix_network",
                                                     "b2c_ekb_drtg_jk_nov_mix_network",
                                                     "b2c_irkutsk_drtg_jk_nov_mix_network",
                                                     "b2c_kaliningrad_drtg_jk_nov_mix_network",
                                                     "b2c_kemerovo_drtg_jk_nov_mix_network",
                                                     "b2c_krasnodar_drtg_jk_nov_mix_network",
                                                     "b2c_novosibirsk_drtg_jk_nov_mix_network",
                                                     "b2c_omsk_drtg_jk_nov_mix_network",
                                                     "b2c_perm_drtg_jk_nov_mix_network",
                                                     "b2c_rostov_drtg_jk_nov_mix_network",
                                                     "b2c_samara_drtg_jk_nov_mix_network",
                                                     "b2c_sevastopol_drtg_jk_nov_mix_network",
                                                     "b2c_sochi_drtg_jk_nov_mix_network",
                                                     "b2c_stavropol_drtg_jk_nov_mix_network",
                                                     "b2c_tyumen_drtg_jk_nov_mix_network",
                                                     "b2c_ufa_drtg_jk_nov_mix_network",
                                                     "b2c_volgograd_drtg_jk_nov_mix_network",
                                                     "b2c_yalta_drtg_jk_nov_mix_network", ]},
        {"descr": 'oth_drtg_jk_nov_bdg', "fltrs": [
            "b2c_arhangelsk_drtg_jk_nov_mix_network",
            "b2c_astrahan_drtg_jk_nov_mix_network",
            "b2c_barnaul_drtg_jk_nov_mix_network",
            "b2c_belgorod_drtg_jk_nov_mix_network",
            "b2c_bryansk_drtg_jk_nov_mix_network",
            "b2c_cheboksary_drtg_jk_nov_mix_network",
            "b2c_habarovsk_drtg_jk_nov_mix_network",
            "b2c_ivanovo_drtg_jk_nov_mix_network",
            "b2c_izhevsk_drtg_jk_nov_mix_network",
            "b2c_kaluga_drtg_jk_nov_mix_network",
            "b2c_kirov_drtg_jk_nov_mix_network",
            "b2c_kostroma_drtg_jk_nov_mix_network",
            "b2c_kurgan_drtg_jk_nov_mix_network",
            "b2c_kursk_drtg_jk_nov_mix_network",
            "b2c_lipetsk_drtg_jk_nov_mix_network",
            "b2c_mahachkala_drtg_jk_nov_mix_network",
            "b2c_novgorod_drtg_jk_nov_mix_network",
            "b2c_orel_drtg_jk_nov_mix_network",
            "b2c_orenburg_drtg_jk_nov_mix_network",
            "b2c_penza_drtg_jk_nov_mix_network",
            "b2c_pskov_drtg_jk_nov_mix_network",
            "b2c_ryazan_drtg_jk_nov_mix_network",
            "b2c_saratov_drtg_jk_nov_mix_network",
            "b2c_smolensk_drtg_jk_nov_mix_network",
            "b2c_surgut_drtg_jk_nov_mix_network",
            "b2c_tambov_drtg_jk_nov_mix_network",
            "b2c_tomsk_drtg_jk_nov_mix_network",
            "b2c_tula_drtg_jk_nov_mix_network",
            "b2c_tver_drtg_jk_nov_mix_network",
            "b2c_ulanude_drtg_jk_nov_mix_network",
            "b2c_ulyanovsk_drtg_jk_nov_mix_network",
            "b2c_vladimir_drtg_jk_nov_mix_network",
            "b2c_vladivostok_drtg_jk_nov_mix_network",
            "b2c_yaroslavl_drtg_jk_nov_mix_network",
        ]},

        ######################################################################################
        # Пакет: RTG salesec #########################################################################
        ######################################################################################
        {"descr": 'msk_salesec_rtg_network_bdg', "fltrs": ["b2c_(mo|msk)_rtg_site_salesec_mix_network", ]},
        {"descr": 'spb_salesec_rtg_network_bdg', "fltrs": ["b2c_spb_rtg_site_salesec_mix_network", ]},
        {"descr": 'p4c_salesec_rtg_network_bdg',
         "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_rtg_site_salesec_mix_network", ]},
        {"descr": 'reg18_salesec_rtg_network_bdg', "fltrs": ["b2c_chelyabinsk_rtg_site_salesec_mix_network",
                                                             "b2c_ekb_rtg_site_salesec_mix_network",
                                                             "b2c_irkutsk_rtg_site_salesec_mix_network",
                                                             "b2c_kaliningrad_rtg_site_salesec_mix_network",
                                                             "b2c_kemerovo_rtg_site_salesec_mix_network",
                                                             "b2c_krasnodar_rtg_site_salesec_mix_network",
                                                             "b2c_novosibirsk_rtg_site_salesec_mix_network",
                                                             "b2c_omsk_rtg_site_salesec_mix_network",
                                                             "b2c_perm_rtg_site_salesec_mix_network",
                                                             "b2c_rostov_rtg_site_salesec_mix_network",
                                                             "b2c_samara_rtg_site_salesec_mix_network",
                                                             "b2c_sevastopol_rtg_site_salesec_mix_network",
                                                             "b2c_sochi_rtg_site_salesec_mix_network",
                                                             "b2c_stavropol_rtg_site_salesec_mix_network",
                                                             "b2c_tyumen_rtg_site_salesec_mix_network",
                                                             "b2c_ufa_rtg_site_salesec_mix_network",
                                                             "b2c_volgograd_rtg_site_salesec_mix_network",
                                                             "b2c_yalta_rtg_site_salesec_mix_network", ]},
        {"descr": 'oth_salesec_rtg_network_bdg', "fltrs": [
            "b2c_arhangelsk_rtg_site_salesec_mix_network",
            "b2c_astrahan_rtg_site_salesec_mix_network",
            "b2c_barnaul_rtg_site_salesec_mix_network",
            "b2c_belgorod_rtg_site_salesec_mix_network",
            "b2c_bryansk_rtg_site_salesec_mix_network",
            "b2c_cheboksary_rtg_site_salesec_mix_network",
            "b2c_habarovsk_rtg_site_salesec_mix_network",
            "b2c_ivanovo_rtg_site_salesec_mix_network",
            "b2c_izhevsk_rtg_site_salesec_mix_network",
            "b2c_kaluga_rtg_site_salesec_mix_network",
            "b2c_kirov_rtg_site_salesec_mix_network",
            "b2c_kostroma_rtg_site_salesec_mix_network",
            "b2c_kurgan_rtg_site_salesec_mix_network",
            "b2c_kursk_rtg_site_salesec_mix_network",
            "b2c_lipetsk_rtg_site_salesec_mix_network",
            "b2c_mahachkala_rtg_site_salesec_mix_network",
            "b2c_novgorod_rtg_site_salesec_mix_network",
            "b2c_orel_rtg_site_salesec_mix_network",
            "b2c_orenburg_rtg_site_salesec_mix_network",
            "b2c_penza_rtg_site_salesec_mix_network",
            "b2c_pskov_rtg_site_salesec_mix_network",
            "b2c_ryazan_rtg_site_salesec_mix_network",
            "b2c_saratov_rtg_site_salesec_mix_network",
            "b2c_smolensk_rtg_site_salesec_mix_network",
            "b2c_surgut_rtg_site_salesec_mix_network",
            "b2c_tambov_rtg_site_salesec_mix_network",
            "b2c_tomsk_rtg_site_salesec_mix_network",
            "b2c_tula_rtg_site_salesec_mix_network",
            "b2c_tver_rtg_site_salesec_mix_network",
            "b2c_ulanude_rtg_site_salesec_mix_network",
            "b2c_ulyanovsk_rtg_site_salesec_mix_network",
            "b2c_vladimir_rtg_site_salesec_mix_network",
            "b2c_vladivostok_rtg_site_salesec_mix_network",
            "b2c_yaroslavl_rtg_site_salesec_mix_network",
        ]},
        ######################################################################################
        # Пакет: RTG rentsec #########################################################################
        ######################################################################################
        {"descr": 'msk_rentsec_rtg_network_bdg', "fltrs": ["b2c_(mo|msk)_rtg_site_rentsec_mix_network", ]},
        {"descr": 'spb_rentsec_rtg_network_bdg', "fltrs": ["b2c_spb_rtg_site_rentsec_mix_network", ]},
        {"descr": 'p4c_rentsec_rtg_network_bdg',
         "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_rtg_site_rentsec_mix_network", ]},
        {"descr": 'reg18_rentsec_rtg_network_bdg', "fltrs": ["b2c_chelyabinsk_rtg_site_rentsec_mix_network",
                                                             "b2c_ekb_rtg_site_rentsec_mix_network",
                                                             "b2c_irkutsk_rtg_site_rentsec_mix_network",
                                                             "b2c_kaliningrad_rtg_site_rentsec_mix_network",
                                                             "b2c_kemerovo_rtg_site_rentsec_mix_network",
                                                             "b2c_krasnodar_rtg_site_rentsec_mix_network",
                                                             "b2c_novosibirsk_rtg_site_rentsec_mix_network",
                                                             "b2c_omsk_rtg_site_rentsec_mix_network",
                                                             "b2c_perm_rtg_site_rentsec_mix_network",
                                                             "b2c_rostov_rtg_site_rentsec_mix_network",
                                                             "b2c_samara_rtg_site_rentsec_mix_network",
                                                             "b2c_sevastopol_rtg_site_rentsec_mix_network",
                                                             "b2c_sochi_rtg_site_rentsec_mix_network",
                                                             "b2c_stavropol_rtg_site_rentsec_mix_network",
                                                             "b2c_tyumen_rtg_site_rentsec_mix_network",
                                                             "b2c_ufa_rtg_site_rentsec_mix_network",
                                                             "b2c_volgograd_rtg_site_rentsec_mix_network",
                                                             "b2c_yalta_rtg_site_rentsec_mix_network", ]},
        {"descr": 'oth_rentsec_rtg_network_bdg', "fltrs": [
            "b2c_arhangelsk_rtg_site_rentsec_mix_network",
            "b2c_astrahan_rtg_site_rentsec_mix_network",
            "b2c_barnaul_rtg_site_rentsec_mix_network",
            "b2c_belgorod_rtg_site_rentsec_mix_network",
            "b2c_bryansk_rtg_site_rentsec_mix_network",
            "b2c_cheboksary_rtg_site_rentsec_mix_network",
            "b2c_habarovsk_rtg_site_rentsec_mix_network",
            "b2c_ivanovo_rtg_site_rentsec_mix_network",
            "b2c_izhevsk_rtg_site_rentsec_mix_network",
            "b2c_kaluga_rtg_site_rentsec_mix_network",
            "b2c_kirov_rtg_site_rentsec_mix_network",
            "b2c_kostroma_rtg_site_rentsec_mix_network",
            "b2c_kurgan_rtg_site_rentsec_mix_network",
            "b2c_kursk_rtg_site_rentsec_mix_network",
            "b2c_lipetsk_rtg_site_rentsec_mix_network",
            "b2c_mahachkala_rtg_site_rentsec_mix_network",
            "b2c_novgorod_rtg_site_rentsec_mix_network",
            "b2c_orel_rtg_site_rentsec_mix_network",
            "b2c_orenburg_rtg_site_rentsec_mix_network",
            "b2c_penza_rtg_site_rentsec_mix_network",
            "b2c_pskov_rtg_site_rentsec_mix_network",
            "b2c_ryazan_rtg_site_rentsec_mix_network",
            "b2c_saratov_rtg_site_rentsec_mix_network",
            "b2c_smolensk_rtg_site_rentsec_mix_network",
            "b2c_surgut_rtg_site_rentsec_mix_network",
            "b2c_tambov_rtg_site_rentsec_mix_network",
            "b2c_tomsk_rtg_site_rentsec_mix_network",
            "b2c_tula_rtg_site_rentsec_mix_network",
            "b2c_tver_rtg_site_rentsec_mix_network",
            "b2c_ulanude_rtg_site_rentsec_mix_network",
            "b2c_ulyanovsk_rtg_site_rentsec_mix_network",
            "b2c_vladimir_rtg_site_rentsec_mix_network",
            "b2c_vladivostok_rtg_site_rentsec_mix_network",
            "b2c_yaroslavl_rtg_site_rentsec_mix_network",
        ]},
        ######################################################################################
        # Пакет: RTG sub #########################################################################
        ######################################################################################
        {"descr": 'msk_sub_rtg_network_bdg', "fltrs": ["b2c_(mo|msk)_rtg_site_sub_mix_network", ]},
        {"descr": 'spb_sub_rtg_network_bdg', "fltrs": ["b2c_spb_rtg_site_sub_mix_network", ]},
        {"descr": 'p4c_sub_rtg_network_bdg',
         "fltrs": ["b2c_(kazan|nn|krasnoyarsk|voronezh)_rtg_site_sub_mix_network", ]},
        {"descr": 'reg18_sub_rtg_network_bdg', "fltrs": ["b2c_chelyabinsk_rtg_site_sub_mix_network",
                                                         "b2c_ekb_rtg_site_sub_mix_network",
                                                         "b2c_irkutsk_rtg_site_sub_mix_network",
                                                         "b2c_kaliningrad_rtg_site_sub_mix_network",
                                                         "b2c_kemerovo_rtg_site_sub_mix_network",
                                                         "b2c_krasnodar_rtg_site_sub_mix_network",
                                                         "b2c_novosibirsk_rtg_site_sub_mix_network",
                                                         "b2c_omsk_rtg_site_sub_mix_network",
                                                         "b2c_perm_rtg_site_sub_mix_network",
                                                         "b2c_rostov_rtg_site_sub_mix_network",
                                                         "b2c_samara_rtg_site_sub_mix_network",
                                                         "b2c_sevastopol_rtg_site_sub_mix_network",
                                                         "b2c_sochi_rtg_site_sub_mix_network",
                                                         "b2c_stavropol_rtg_site_sub_mix_network",
                                                         "b2c_tyumen_rtg_site_sub_mix_network",
                                                         "b2c_ufa_rtg_site_sub_mix_network",
                                                         "b2c_volgograd_rtg_site_sub_mix_network",
                                                         "b2c_yalta_rtg_site_sub_mix_network", ]},
        {"descr": 'oth_sub_rtg_network_bdg', "fltrs": [
            "b2c_arhangelsk_rtg_site_sub_mix_network",
            "b2c_astrahan_rtg_site_sub_mix_network",
            "b2c_barnaul_rtg_site_sub_mix_network",
            "b2c_belgorod_rtg_site_sub_mix_network",
            "b2c_bryansk_rtg_site_sub_mix_network",
            "b2c_cheboksary_rtg_site_sub_mix_network",
            "b2c_habarovsk_rtg_site_sub_mix_network",
            "b2c_ivanovo_rtg_site_sub_mix_network",
            "b2c_izhevsk_rtg_site_sub_mix_network",
            "b2c_kaluga_rtg_site_sub_mix_network",
            "b2c_kirov_rtg_site_sub_mix_network",
            "b2c_kostroma_rtg_site_sub_mix_network",
            "b2c_kurgan_rtg_site_sub_mix_network",
            "b2c_kursk_rtg_site_sub_mix_network",
            "b2c_lipetsk_rtg_site_sub_mix_network",
            "b2c_mahachkala_rtg_site_sub_mix_network",
            "b2c_novgorod_rtg_site_sub_mix_network",
            "b2c_orel_rtg_site_sub_mix_network",
            "b2c_orenburg_rtg_site_sub_mix_network",
            "b2c_penza_rtg_site_sub_mix_network",
            "b2c_pskov_rtg_site_sub_mix_network",
            "b2c_ryazan_rtg_site_sub_mix_network",
            "b2c_saratov_rtg_site_sub_mix_network",
            "b2c_smolensk_rtg_site_sub_mix_network",
            "b2c_surgut_rtg_site_sub_mix_network",
            "b2c_tambov_rtg_site_sub_mix_network",
            "b2c_tomsk_rtg_site_sub_mix_network",
            "b2c_tula_rtg_site_sub_mix_network",
            "b2c_tver_rtg_site_sub_mix_network",
            "b2c_ulanude_rtg_site_sub_mix_network",
            "b2c_ulyanovsk_rtg_site_sub_mix_network",
            "b2c_vladimir_rtg_site_sub_mix_network",
            "b2c_vladivostok_rtg_site_sub_mix_network",
            "b2c_yaroslavl_rtg_site_sub_mix_network",
        ]},
    ]

    def __init__(self):
        for i in self.mp_map:
            i['fltrs'] = [re.compile(j) for j in i['fltrs']]

    def __getitem__(self, item):
        for i in self.mp_map:
            for j in i['fltrs']:
                if j.search(item):
                    return i['descr']

        return False


class GroupsRegions:
    regs = [
        {"descr": 'msk', "fltrs": ["_msk_", "_mo_", "_dmo_", "_bmo_", "_mskmo_"]},
        {"descr": 'spb', "fltrs": ["_spb_", "_spblo_"]},
        {"descr": 'p4c', "fltrs": ["_kazan_", "_nn_", "_krasnoyarsk_", "voronezh"]},
        {"descr": '18reg', "fltrs": ['ufa',
                                     'krasnodar',
                                     'sochi',
                                     'rostov',
                                     'samara',
                                     'ekb',
                                     'novosibirsk',
                                     'chelyabinsk',
                                     'tyumen',
                                     'stavropol',
                                     'yalta',
                                     'omsk',
                                     'volgograd',
                                     'kemerovo',
                                     'irkutsk',
                                     'sevastopol',
                                     'kaliningrad',
                                     'perm']},

        {"descr": 'oth', "fltrs": ['rf',
                                 'arhangelsk',
                                 'astrahan',
                                 'barnaul',
                                 'belgorod',
                                 'bryansk',
                                 'cheboksary',
                                 'habarovsk',
                                 'ivanovo',
                                 'izhevsk',
                                 'kaluga',
                                 'kirov',
                                 'kostroma',
                                 'kurgan',
                                 'kursk',
                                 'lipetsk',
                                 'mahachkala',
                                 'novgorod',
                                 'orel',
                                 'orenburg',
                                 'penza',
                                 'pskov',
                                 'ryazan',
                                 'saratov',
                                 'smolensk',
                                 'surgut',
                                 'tambov',
                                 'tomsk',
                                 'tula',
                                 'tver',
                                 'ulanude',
                                 'ulyanovsk',
                                 'vladimir',
                                 'vladivostok',
                                 'yaroslavl']},

    ]

    def __init__(self):
        for i in self.regs:
            i['fltrs'] = [re.compile(j) for j in i['fltrs']]

    def __getitem__(self, item):
        for i in self.regs:
            for j in i['fltrs']:
                if j.search(item):
                    return i['descr']

        return False


if __name__ == '__main__':
    mp = MP()
    print(mp["b2b_ekb_general_null_own_desk_search"])
    print(mp["b2b_ZZZ_general_null_own_desk_search"])
